import { TechIconMap } from '@typings/techIcons'
import {
  Api,
  Astro,
  Async,
  Command,
  CSS,
  Cursor,
  Discordjs,
  Docker,
  Electron,
  Expressjs,
  Figma,
  Handlebars,
  HTML5,
  JavaScript,
  JWT,
  LogisticsManagement,
  MaterialUI,
  MongoDB,
  Motion,
  NestJS,
  Nextjs,
  Nodejs,
  Postman,
  React,
  Sass,
  TailwindCSS,
  TypeScript,
  VisualStudioCode,
  Web,
  Windows,
} from "@icons";

export const techIcons: TechIconMap = {
  apiintegration: <Api className="size-4 stroke-1" />,
  apiqrcodegenerator: <Api className="size-4 stroke-1" />,
  astro: <Astro className="size-4 stroke-1" />,
  asynchronouslogic: <Async className="size-4 stroke-1" />,
  commandhandler: <Command className="size-4 stroke-1" />,
  css: <CSS className="size-4 stroke-1" />,
  cursor: <Cursor className="size-4 stroke-1" />,
  discordjs: <Discordjs className="size-4 stroke-1" />,
  docker: <Docker className="size-4 stroke-1" />,
  electronjs: <Electron className="size-4 stroke-1" />,
  express: <Expressjs className="size-4 stroke-1" />,
  figma: <Figma className="size-4 stroke-1" />,
  uiuxdesign: <Figma className="size-4 stroke-1" />,
  handlebars: <Handlebars className="size-4 stroke-1" />,
  html: <HTML5 className="size-4 stroke-1" />,
  javascript: <JavaScript className="size-4 stroke-1" />,
  jwtauthentication: <JWT className="size-4 stroke-1" />,
  logisticsmanagement: <LogisticsManagement className="size-4 stroke-1" />,
  inventorymanagement: <LogisticsManagement className="size-4 stroke-1" />,
  materialui: <MaterialUI className="size-4 stroke-1" />,
  mongodb: <MongoDB className="size-4 stroke-1" />,
  motion: <Motion className="size-4 stroke-1" />,
  nestjs: <NestJS className="size-4 stroke-1" />,
  nextjs: <Nextjs className="size-4 fill-black" />,
  nodejs: <Nodejs className="size-4 stroke-1" />,
  postman: <Postman className="size-4 stroke-1" />,
  reactjs: <React className="size-4 stroke-1" />,
  scss: <Sass className="size-4 stroke-1" />,
  tailwindcss: <TailwindCSS className="size-4 stroke-1" />,
  typescript: <TypeScript className="size-4 stroke-1" />,
  visualstudiocode: <VisualStudioCode className="size-4 stroke-1" />,
  webapp: <Web className="size-4 stroke-1" />,
  windowsapp: <Windows className="size-4 stroke-1" />,
};
